'use strict';
const faqData = [{"q": "दुकान कब खुलती है?", "aliases": ["timings", "opening hours", "समय", "दुकान का समय"], "a": "सोमवार से शनिवार: सुबह 9:30 से दोपहर 2:00 और शाम 4:30 से रात 8:00। दोपहर 2:00 से 4:30 विराम। रविवार बंद।"}, {"q": "कौन-कौन सी सेवाएँ हैं?", "aliases": ["services", "सेवाएँ", "services available"], "a": "PAN, CSC रेल टिकट, बीमा, आयुष्मान सहायता, पासपोर्ट आवेदन सहायता, वाहन प्रदूषण/PUC संबंधी सहायता, ड्राइविंग लाइसेंस और RTO संबंधी सहायता।"}, {"q": "दुकान कहाँ है?", "aliases": ["location", "address", "दुकान की लोकेशन"], "a": "Barna, Prayagraj। संपर्क सेक्शन का Google Maps बटन owner की साझा की गई shop location खोलता है।"}, {"q": "PAN के लिए कौन से दस्तावेज़ चाहिए?", "aliases": ["pan documents", "pan दस्तावेज़"], "a": "पहचान, पता और जन्म तारीख का प्रमाण तैयार रखें। इसी पेज के PAN दस्तावेज़ सेक्शन में छोटी सूची और Protean की पूरी सूची का link है। आवेदन से पहले पूरी सूची जाँचें।"}, {"q": "Appointment कैसे लें?", "aliases": ["appointment", "booking", "appointment request"], "a": "हर appointment 15 मिनट का है। ऊपर request form में नाम, मोबाइल, सेवा और पसंदीदा समय भरें। संदेश review/copy करके WhatsApp पर भेजें। Live availability अभी Unavailable है। Business की पुष्टि के बाद ही समय तय होगा।"}, {"q": "संपर्क कैसे करें?", "aliases": ["contact", "email", "whatsapp", "संपर्क"], "a": "हरे WhatsApp बटन से business से बात करें। Email बटन आपके mail app में business email खोलता है। Facebook, Instagram और YouTube links संपर्क सेक्शन में हैं।"}];
const normalise=s=>s.trim().toLowerCase().replace(/[?？।]/g,'');
const whatsapp = document.querySelector('#visit a[href*="wa.me"]').href;
function greenLink(text){const a=document.createElement('a');a.href=whatsapp;a.className='wa-open';a.target='_blank';a.rel='noopener noreferrer';a.textContent=text;return a;}
document.querySelectorAll('.service-toggle').forEach(button=>button.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')==='true';document.querySelectorAll('.service-toggle').forEach(b=>{b.setAttribute('aria-expanded','false');document.getElementById(b.getAttribute('aria-controls')).hidden=true;b.querySelector('.service-more').textContent='जानकारी देखें +';});if(!open){button.setAttribute('aria-expanded','true');document.getElementById(button.getAttribute('aria-controls')).hidden=false;button.querySelector('.service-more').textContent='बंद करें −';}}));
const panButton=document.querySelector('#documents button');panButton.addEventListener('click',()=>{const panel=document.getElementById('pan-list');panel.hidden=!panel.hidden;panButton.setAttribute('aria-expanded',String(!panel.hidden));panButton.textContent=panel.hidden?'दस्तावेज़ों की सूची खोलें':'सूची बंद करें';});
document.querySelector('form[data-form="faq"]').addEventListener('submit',e=>{e.preventDefault();const q=e.currentTarget.querySelector('input').value;const n=normalise(q);const match=faqData.find(f=>[f.q,...f.aliases].some(a=>normalise(a)===n));const panel=document.querySelector('.faq-answer');panel.replaceChildren();const p=document.createElement('p');p.textContent=match?match.a:'यह जानकारी यहाँ उपलब्ध नहीं है। कृपया WhatsApp पर पूछें। Unavailable here, please ask on WhatsApp.';panel.append(p,greenLink('WhatsApp'));panel.hidden=false;panel.scrollIntoView({block:'nearest',behavior:'smooth'});});
document.querySelector('form[data-form="enquiry"]').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get('fullName')).trim();if(!name)return;const message=`Prayagi Store & Services - enquiry / appointment request\nName: ${name}\nMobile: ${data.get('mobile')}\nService: ${data.get('service')}\nRequested date: ${data.get('date')||'Not selected'}\nRequested times (15 min each): ${data.get('times')||'Not selected'}\nMessage: ${data.get('message')||'-'}\nPlease check availability and confirm. This is a request, not a booking.`;
const panel=document.querySelector('.request-preview');panel.replaceChildren();const heading=document.createElement('h3');heading.textContent='भेजने से पहले देखें';const pre=document.createElement('pre');pre.textContent=message;const status=document.createElement('p');status.setAttribute('role','status');status.textContent='संदेश copy करें, फिर WhatsApp में paste करके भेजें।';const copy=document.createElement('button');copy.type='button';copy.className='prepare-button';copy.textContent='संदेश copy करें';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(message);status.textContent='Copy हो गया। WhatsApp में paste करके भेजें।';}catch{const range=document.createRange();range.selectNodeContents(pre);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);status.textContent='संदेश चुन लिया गया है। अपने device के Copy विकल्प का उपयोग करें, फिर WhatsApp में paste करें।';}});const note=document.createElement('p');note.className='file-caption';note.textContent='हम यहाँ से message नहीं भेजते। भेजने और business की पुष्टि के बाद ही appointment तय होगा।';panel.append(heading,pre,copy,greenLink('WhatsApp खोलें'),status,note);panel.hidden=false;panel.scrollIntoView({block:'nearest',behavior:'smooth'});});
